# config
name: ecommerce
url: "https://ecommerce-raw-bart.s3.us-east-1.amazonaws.com"

# Profile information
author: "Cesar Augusto"
title: ""

# Meta Tag
description: > # this means to ignore newlines until "baseurl:"
  Site para vizualização dos produtos e recomendações baseadas 
  na interação do usuario

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README*

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  style: compressed

plugins:
  - jekyll-datapage-generator  

page_gen:
  - index_files: true
    data: products
    template: product
    name: sku
    dir: products
